### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by amosfong** [comment]
@peterfellwock FYI, if you want to take a look

**Comment by amosfong** [comment]
Hey Ray,

Since you needed to add the license.impl jar into portal.properties, then I'll need to include all old versions in one license impl.jar right?

**Comment by rotty3000** [comment]
No, you can simply leave the version number on the jar file name, and add
each one there in the list.

- Ray

On Wed, Nov 11, 2015 at 4:59 PM, Amos Fong <notifications@github.com> wrote:

> Hey Ray,
>
> Since you needed to add the license.impl jar into portal.properties, then
> I'll need to include all old versions in one license impl.jar right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amosfong/liferay-portal/pull/23#issuecomment-155922844>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by amosfong** [comment]
I'm imagining if a customer needs to update their license-impl.jar, they would also have to modify portal-ext.properties as well then?

One other question:
I see on restart bundles aren't resolved again. So say a license expires, will it continue to work indefinitely until the /state folder is deleted?

**Comment by rotty3000** [comment]
On Wed, Nov 11, 2015 at 5:24 PM, Amos Fong <notifications@github.com> wrote:

> I'm imagining if a customer needs to update their license-impl.jar, they
> would also have to modify portal-ext.properties as well then?
>
> One other question:
> I see on restart bundles aren't resolved again. So say a license expires,
> will it continue to work indefinitely until the /state folder is deleted?
>
That's a good question. Resolve does indeed persist. However you could
trigger a check by forcing a resolve of all the bundles.

I'm not sure how aggressive you want to be with the expiration check. Do
you want it to blow up the system? or do you want to just log a very noise
warning that some module license has expired... maybe with a grace period
at WARN before reaching FATAL level.

- Ray


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amosfong/liferay-portal/pull/23#issuecomment-155928694>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by amosfong** [comment]
If it can be checked on every restart or redeploy of jar, that would be sufficient.

**Comment by rotty3000** [comment]
>  I'm imagining if a customer needs to update their license-impl.jar, they would also have to modify portal-ext.properties as well then?

If you want the impl bundles could also go in the core dir. We'd have to wire them in the same way we did with the hook... just they wouldn't be hooks. This way they trigger before any other bundles would and that's what we want here.

**Comment by rotty3000** [comment]
redeploy is already covered because it requires a resolve to take place,
which we've got.

On Wed, Nov 11, 2015 at 5:31 PM, Amos Fong <notifications@github.com> wrote:

> If it can be checked on every restart or redeploy of jar, that would be
> sufficient.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amosfong/liferay-portal/pull/23#issuecomment-155930182>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by amosfong** [comment]
sorry I meant to say restart *AND redeploy of the jar.

**Comment by rotty3000** [comment]
doing a check on restart I have to look at the best way to do it without
killing all the resolution which will be costly.

On Wed, Nov 11, 2015 at 5:33 PM, Raymond Auge <raymond.auge@liferay.com>
wrote:

> redeploy is already covered because it requires a resolve to take place,
> which we've got.
>
> On Wed, Nov 11, 2015 at 5:31 PM, Amos Fong <notifications@github.com>
> wrote:
>
>> If it can be checked on every restart or redeploy of jar, that would be
>> sufficient.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/amosfong/liferay-portal/pull/23#issuecomment-155930182>
>> .
>>
>
>
>
> --
> *Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
>  (@rotty3000)
> Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
>  (@Liferay)
> Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org>
> (@OSGiAlliance)
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by amosfong** [comment]
>If you want the impl bundles could also go in the core dir. We'd have to wire them in the same way we >did with the hook... just they wouldn't be hooks. This way they trigger before any other bundles would >and that's what we want here.

ok, I'll look into this

**Pull request closed without merging**
