### PR TITLE
LRQA-33105 Add portal license batch test to pull request tester

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-33276

The file "masterList" is a placeholder for an official list that should be provided by Amos Fong
Source:
https://issues.liferay.com/browse/LRQA-33105

@amosfong I'm sending this pull to you so you can provide the "masterList" before sending to BChan.

CC @yichenroy

### CODE REVIEW

**Comment by amosfong** [comment]
Thanks @pyoo47! So I just put a return delimited list of files in masterList and then send everything to BChan?

**Comment by pyoo47** [comment]
@amosfong Yes, it should be return delimited in the masterList file. After a bit of reflection, I think it might be a good idea to rename the file to be something more descriptive. If you can come up with a better name for the file, I can make the necessary code changes to support the new file name.

CC: @yichenroy

**Comment by amosfong** [comment]
merged, thanks!

https://github.com/brianchandotcom/liferay-portal/pull/50510

maybe watchList or something similar?

**Comment by pyoo47** [comment]
@amosfong @yichenroy How about licensingWatchList?

**Comment by amosfong** [comment]
Sounds good to me

**Comment by pyoo47** [comment]
@amosfong OK. Can you close your pull to BChan then? I'll do the name change and then send everything to him.

**Comment by yichenroy** [comment]
Sounds good to me too

**Comment by amosfong** [comment]
ok, closed it.

**Pull request closed without merging**
