### PR TITLE
Lps 143575

### PR DESCRIPTION
**Pull request by amosfong**

### CODE REVIEW

**Comment by amosfong** [comment]
ci:test

**Comment by amosfong** [comment]
ci:test

**Comment by amosfong** [comment]
Hey @vicnate5, I keep getting seemingly unrelated errors. Can you help? THanks!

Are these issues with CI? or are they valid? they don't seem like they would be caused by changes.

https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6/18753//consoleText
Looks like a GC allocation error?

https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=12/3437//consoleText
[beanshell] java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to create local branch master-temp-1644546877654 at 306edce04bb3c391c9f40f79ff6a41435327f4df
[beanshell] error: inflate: data stream error (incorrect data check)
[beanshell] fatal: packed object 5146eb6948b890fbfcfaf70626f65063912e6687 (stored in .git/objects/pack/pack-1a06a9c8a6c6caf38ac3c087e7266d9344cef062.pack) is corrupt

https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=10/28086//consoleText
     [java] com.microsoft.sqlserver.jdbc.SQLServerException: Cannot open database "lportal" requested by the login. The login failed. ClientConnectionId:4de281df-95fd-42d0-8221-52c07a8d4408

https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=11/28086//consoleText
     [java] 2022-02-11 02:52:05.459 ERROR [main][UpgradeStepRegistratorTracker:221] Failed upgrade process for module com.liferay.message.boards.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.microsoft.sqlserver.jdbc.SQLServerException: Transaction (Process ID 51) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

**Comment by zhangyan0701** [comment]
Hi @amosfong 

There are two source formatting issues in file "portal-impl/src/com/liferay/portal/upgrade/v7_4_x/UpgradeExternalReferenceCode.java":

```
     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: Use method 'StringBundler.concat' when concatenating more than 3 strings, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/java_multi_plus_concat_check.markdown: ./portal-impl/src/com/liferay/portal/upgrade/v7_4_x/UpgradeExternalReferenceCode.java 88 (SourceCheck:JavaMultiPlusConcatCheck)
     [java] 2: ./portal-impl/src/com/liferay/portal/upgrade/v7_4_x/UpgradeExternalReferenceCode.java expected:<...= new StringBundler([5]);
     [java] 
     [java] 		updateSB.appen...> but was:<...= new StringBundler([4]);
     [java] 
     [java] 		updateSB.appen...>
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:435)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:281)
```
Full console:
https://testray.liferay.com/reports/production/logs/2022-02/test-1-35/test-portal-acceptance-pullrequest(master)/703/source-format-jdk8/0/0/jenkins-console.txt.gz?authuser=0

Other failures are unrelated.

**Comment by amosfong** [comment]
@[zhangyan0701 ok thank you!

**Pull request closed without merging**
